# Generated by Django 6.0.3 on 2026-03-28 19:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('montant_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nombre_participants', models.IntegerField()),
                ('participants_payes', models.IntegerField(default=0)),
                ('montant_collecte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nb_jours', models.IntegerField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_expiration', models.DateTimeField()),
                ('statut', models.CharField(choices=[('active', 'Active'), ('complete', 'Complete'), ('expiree', 'Expiree'), ('stoppee', 'Stoppee')], default='active', max_length=20)),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('deep_link', models.CharField(max_length=100)),
                ('qr_token', models.TextField(blank=True)),
                ('prix_modifiable', models.BooleanField(default=False)),
                ('numero_receveur', models.CharField(max_length=20)),
                ('sendavapay_invoice_url', models.URLField(blank=True)),
                ('rappel_envoye', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('date_suppression', models.DateTimeField(blank=True, null=True)),
                ('date_stop', models.DateTimeField(blank=True, null=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotisations_creees', to=settings.AUTH_USER_MODEL)),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotisations_supprimees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cotisations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('reponse_admin', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('supprime', models.BooleanField(default=False)),
                ('date_suppression', models.DateTimeField(blank=True, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL)),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='cotisations.cotisation')),
            ],
            options={
                'db_table': 'commentaires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='NotationCreateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notations', to='cotisations.cotisation')),
                ('noteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_donnees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notations_createurs',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_par_unite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nb_unites', models.IntegerField(default=1)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Paye'), ('rembourse', 'Rembourse')], default='en_attente', max_length=20)),
                ('date_participation', models.DateTimeField(default=django.utils.timezone.now)),
                ('rang_paiement', models.IntegerField(default=0)),
                ('sendavapay_token', models.CharField(blank=True, max_length=255)),
                ('participation_id', models.CharField(max_length=20, unique=True)),
                ('qr_token', models.TextField(blank=True)),
                ('supprime', models.BooleanField(default=False)),
                ('date_suppression', models.DateTimeField(blank=True, null=True)),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='cotisations.cotisation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'participations',
            },
        ),
        migrations.AddIndex(
            model_name='cotisation',
            index=models.Index(fields=['slug'], name='cotisations_slug_e41918_idx'),
        ),
        migrations.AddIndex(
            model_name='cotisation',
            index=models.Index(fields=['createur', 'statut'], name='cotisations_createu_f9c710_idx'),
        ),
        migrations.AddIndex(
            model_name='cotisation',
            index=models.Index(fields=['date_expiration'], name='cotisations_date_ex_308f33_idx'),
        ),
        migrations.AddIndex(
            model_name='cotisation',
            index=models.Index(fields=['supprime'], name='cotisations_supprim_3ba208_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notationcreateur',
            unique_together={('cotisation', 'noteur')},
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['cotisation', 'statut'], name='participati_cotisat_2705ad_idx'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['participant'], name='participati_partici_5ef49c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('cotisation', 'participant')},
        ),
    ]
