# Generated by Django 6.0.3 on 2026-03-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('paiement_recu', 'Paiement recu'), ('cotisation_complete', 'Cotisation complete'), ('cotisation_expiree', 'Cotisation expiree'), ('verification_approuvee', 'Verification approuvee'), ('verification_rejetee', 'Verification rejetee'), ('sanction', 'Sanction'), ('remboursement', 'Remboursement'), ('rappel', 'Rappel'), ('systeme', 'Systeme')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('data', models.JSONField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
