# Generated by Django 6.0.3 on 2026-03-13 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quickpay', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quickpay',
            name='createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quickpays_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quickpay',
            name='payeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quickpays_payes', to=settings.AUTH_USER_MODEL),
        ),
    ]
