# Generated by Django 6.0.3 on 2026-03-28 11:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pseudo', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('whatsapp_numero', models.CharField(blank=True, max_length=20)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('email_verifie', models.BooleanField(default=False)),
                ('whatsapp_verifie', models.BooleanField(default=False)),
                ('niveau', models.CharField(choices=[('basique', 'Basique'), ('verifie', 'Verifie'), ('business', 'Business')], default='basique', max_length=20)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('banni', 'Banni'), ('supprime', 'Supprime')], default='actif', max_length=20)),
                ('identite_verifiee', models.BooleanField(default=False)),
                ('numero_cni_hash', models.CharField(blank=True, max_length=64)),
                ('photo_cni_recto', models.URLField(blank=True)),
                ('photo_cni_verso', models.URLField(blank=True)),
                ('statut_verification', models.CharField(choices=[('non_soumis', 'Non soumis'), ('en_attente', 'En attente'), ('approuve', 'Approuve'), ('rejete', 'Rejete')], default='non_soumis', max_length=20)),
                ('nom_verrouille', models.BooleanField(default=False)),
                ('prenom_verrouille', models.BooleanField(default=False)),
                ('date_limite_verification', models.DateTimeField(blank=True, null=True)),
                ('code_parrainage', models.CharField(blank=True, max_length=8, unique=True)),
                ('nb_parrainages_actifs', models.IntegerField(default=0)),
                ('note_moyenne', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('nb_notes_recues', models.IntegerField(default=0)),
                ('nb_cotisations_completes', models.IntegerField(default=0)),
                ('theme_preference', models.CharField(choices=[('bleu', 'Bleu Classic'), ('vert', 'Vert Afrique'), ('violet', 'Violet Premium')], default='bleu', max_length=10)),
                ('mode_preference', models.CharField(choices=[('sombre', 'Sombre'), ('clair', 'Clair')], default='sombre', max_length=10)),
                ('fcm_token', models.TextField(blank=True)),
                ('ville_approx', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default='TG', max_length=2)),
                ('admin_role', models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('moderateur', 'Moderateur'), ('support', 'Support'), ('finance', 'Finance'), ('verification', 'Verification'), ('lecteur', 'Lecteur')], max_length=20, null=True)),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_suppression', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('parrain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filleuls', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='SessionDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_connexion', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_derniere_activite', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session_devices',
            },
        ),
        migrations.CreateModel(
            name='VerificationObligatoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_limite', models.DateTimeField()),
                ('notif_envoyee', models.BooleanField(default=False)),
                ('compte_ferme', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verif_obligatoire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_obligatoire',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['pseudo'], name='users_pseudo_63a3db_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['telephone'], name='users_telepho_dce4c6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['niveau'], name='users_niveau_739f88_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['statut'], name='users_statut_34586c_idx'),
        ),
        migrations.AddIndex(
            model_name='sessiondevice',
            index=models.Index(fields=['user', 'is_active'], name='session_dev_user_id_818229_idx'),
        ),
    ]
